spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user?currentSchema=public
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  liquibase:
    user: postgres
    password: postgres
    change-log: classpath:/db/main.yaml
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect